name: flutterbook
description: A storyboard tool to accelerate the development of Flutter widgets.
version: 0.1.10
homepage: https://github.com/GhostWalker562/flutterbook

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  device_preview: ^1.2.0
  flutter_markdown: ^0.7.6+2
  dart_code_viewer2: ^1.0.2
  flutter_feather_icons: ^2.0.0+1
  google_fonts: ^6.2.1
  provider: ^6.1.2
  recase: ^4.1.0

dev_dependencies:
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter

flutter:
